name: fizz-buzz-ruby
services:
  app:
    type: ruby:2.5
    command: tail -f /dev/null
    build:
      - gem install bundle
      - bundle install
tooling:
  rspec:
    service: app
    description: Executes rspec to run tests.
    cmd: 'rspec'
