name: fizz-buzz-ruby
services:
  main:
    type: compose
    services:
      image: ruby:2.7
      command: tail -f /dev/null
    build:
      - bundle install --gemfile=/app/Gemfile
      - chmod +x /app/bin/fizzbuzz
tooling:
  fizzbuzz:
    service: main
    cmd: /app/bin/fizzbuzz
  lint:
    service: main
    cmd: bundle exec rubocop
    dir: /app
  test:
    service: main
    cmd: bundle exec rspec
    dir: /app
