#!/usr/bin/ruby
# frozen_string_literal: true

##
# FizzBuzz entry point.

require_relative 'lib/fizzbuzz.rb'

# Limit must be defined.
limit = ARGV.first.to_i
raise 'A limit (number) must be specified.' unless limit.positive?

# Generate FizzBuzz
output = FizzBuzz.process_range 1, limit
puts output.join("\n") + "\n"

exit 0
