#!/usr/bin/ruby
# frozen_string_literal: true

##
# FizzBuzz entry point.

# Limit must be defined.
limit = ARGV.first.to_i
raise 'A limit (number) must be specified.' unless limit.positive?

# Generate FizzBuzz
require_relative 'lib/fizzbuzz.rb'
puts FizzBuzz.process_range 0, limit
